# Intro to Numpy

[Here](http://cs231n.github.io/python-numpy-tutorial/#python-sets) is a Numpy tutorial.

**Numpy** is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. 
A **numpy array** is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the **rank** of the array; the **shape** of an array is a tuple of integers giving the size of the array along each dimension.

In [1]:
import numpy as np
import pandas as pd

## Vectors

In [2]:
# A vector:
v = np.array([1,2,3])
v

array([1, 2, 3])

In [3]:
type(v)

numpy.ndarray

In [4]:
list(v)

[1, 2, 3]

In [5]:
v[0]

1

In [6]:
# Dot product of two vectors:
w = np.array([100,10,1])

print(np.dot(v, w))

123


## Matrices

In [7]:
#A matrix:
m = np.array([[0,1],[2,3]])
m

array([[0, 1],
       [2, 3]])

In [8]:
print(m)

[[0 1]
 [2 3]]


In [9]:
m[1,1]

3

In [10]:
m[1,1]=4
m

array([[0, 1],
       [2, 4]])

In [11]:
print(m.shape)            #Dimension of the array

(2, 2)


In [12]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
b

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
b.shape

(2, 3)

In [14]:
(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

(1, 2, 4)

In [15]:
#Matrix times vector:
m = np.array([[1,10],[100,1000]])
v = np.array([1,2])
np.dot(m, v)

array([  21, 2100])

In [16]:
#Matrix times matrix:
m1 = np.array([[1,2],[3,4],[5,6]])
m2 = np.array([[5,6],[7,8]])
np.dot(m1, m2)

array([[19, 22],
       [43, 50],
       [67, 78]])

## Descriptive statistics

In [17]:
df = pd.read_csv('../datasets/GDP-2015.csv')
gdp = df['GDP per capita']

In [18]:
import numpy
print( "Mean GDP is", np.mean(gdp) )
print( "Standard deviation is", np.std(gdp) )
print( "Count is", np.count_nonzero(gdp) )
print( "Minimum GDP is", min(gdp) )
print( "Maximum GDP is", max(gdp) )
print( "25 percentile of GDP is", np.percentile(gdp, 25) )
print( "50 percentile of GDP is", np.percentile(gdp, 50) )
print( "75 percentile of GDP is", np.percentile(gdp, 75) )
print( "Sum is", np.sum(gdp) )
print( "Median is", np.median(gdp) )

Mean GDP is 18216.59880239521
Standard deviation is 19247.477664769667
Count is 167
Minimum GDP is 605
Maximum GDP is 139542
25 percentile of GDP is 3705.0
50 percentile of GDP is 11738.0
75 percentile of GDP is 25843.0
Sum is 3042172
Median is 11738.0


## Random numbers

In [19]:
np.random.rand()

0.5414489019847767

In [20]:
np.random.rand(10)

array([0.2492588 , 0.50351535, 0.59080497, 0.94918223, 0.4525798 ,
       0.68689585, 0.8852254 , 0.89561959, 0.03399215, 0.67345664])